#!/usr/bin/env bash
# mwboot bootloader - generated by bake-off. One file, one command:
#
#     bash mwboot-bakeoff.sh
#
# It makes THIS machine's GPUs available to the bake-off that generated it:
#   1. verifies the NVIDIA driver and python3,
#   2. installs vLLM into a venv if no python here can import it,
#   3. starts one mwboot-control swap agent per GPU (keyed to your bake-off),
#   4. enrolls each GPU back to bake-off - the machine appears in
#      Settings > Machines by itself. No JSON to paste, no dashboard password here.
#
# Re-running is always safe: agents restart in place, enrollment updates rather
# than duplicates. To hand the box back: evacuate it from bake-off, then
# `pkill -f mwboot-control` here; cached weights live in ~/.cache/huggingface.
#
# MWBOOT_DRY=1 bash mwboot-bakeoff.sh   -> full flow with simulated GPUs/loads
set -uo pipefail

MP_URL="__MP_URL__"          # the bake-off that generated this file
TOKEN="__TOKEN__"            # enrollment token (expires; regenerate in Settings > Machines)
CKEY="__CKEY__"              # control key: only this bake-off may swap models here
BASE_PORT="${MWBOOT_BASE_PORT:-8001}"     # vLLM endpoint for GPU i = BASE_PORT+i
CTRL_BASE="${MWBOOT_CTRL_BASE:-11500}"    # agent for GPU i = CTRL_BASE+i
MAXLEN="${MWBOOT_MAX_LEN:-8192}"
VLLM_ARGS="${MWBOOT_VLLM_ARGS:---enforce-eager --trust-remote-code}"
DRY="${MWBOOT_DRY:-0}"
AGENT_DIR="$HOME/.local/share/mwboot"

c(){ printf '\033[1;36m[mwboot]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[mwboot] %s\033[0m\n' "$*"; }
die(){ printf '\033[1;31m[mwboot] %s\033[0m\n' "$*" >&2; exit 1; }

# ---------- 1. preflight ----------
command -v curl >/dev/null || die "curl is required."
command -v python3 >/dev/null || die "python3 is required."
if [ "$DRY" != 1 ]; then
  command -v nvidia-smi >/dev/null || die "nvidia-smi not found - install the NVIDIA driver first, then re-run."
fi

# ---------- 2. detect GPUs ----------
if [ "$DRY" = 1 ]; then
  GPU_ROWS=("0, DRY GPU, 24000" "1, DRY GPU, 24000")
  warn "(dry mode) simulating 2 GPUs; no vLLM will run"
else
  mapfile -t GPU_ROWS < <(nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader,nounits)
  [ "${#GPU_ROWS[@]}" -gt 0 ] || die "no NVIDIA GPUs detected."
fi
c "Detected ${#GPU_ROWS[@]} GPU(s):"
for r in "${GPU_ROWS[@]}"; do printf '        GPU %s\n' "$r"; done

# ---------- 3. a python that can import vllm (install into ~/mwboot-env if none) ----------
VENVPY=""
if [ "$DRY" != 1 ]; then
  for p in "$HOME/vllm-env/bin/python3" "$HOME/mwboot-env/bin/python3" "$(command -v python3)"; do
    [ -x "$p" ] && "$p" -c "import vllm" >/dev/null 2>&1 && { VENVPY="$p"; break; }
  done
  if [ -z "$VENVPY" ]; then
    c "Installing vLLM into ~/mwboot-env (first time takes a few minutes)..."
    python3 -m venv "$HOME/mwboot-env" || die "python3 -m venv failed (install the python3-venv package), then re-run."
    "$HOME/mwboot-env/bin/pip" install -q -U pip || die "pip upgrade failed - check the network, then re-run."
    "$HOME/mwboot-env/bin/pip" install -q vllm || die "vLLM install failed - see pip's message above, then re-run."
    VENVPY="$HOME/mwboot-env/bin/python3"
  fi
  c "vLLM python: $VENVPY"
fi

# ---------- 4. unpack the embedded swap agent ----------
mkdir -p "$AGENT_DIR"
base64 -d > "$AGENT_DIR/mwboot-control.py" <<'AGENT_B64'
__AGENT_B64__
AGENT_B64
python3 - "$AGENT_DIR/mwboot-control.py" <<'PY' || die "embedded agent failed to parse - re-download the bootloader."
import py_compile, sys; py_compile.compile(sys.argv[1], doraise=True)
PY

# ---------- 5. one agent per GPU (restart in place; sequential loads are the agent's job) ----------
i=0
declare -a CTRLS PORTS IDXS NAMES VRAMS
for r in "${GPU_ROWS[@]}"; do
  idx=$(awk -F',' '{gsub(/ /,"",$1);print $1}' <<< "$r")
  gname=$(awk -F',' '{sub(/^ */,"",$2);print $2}' <<< "$r")
  vram=$(awk -F',' '{gsub(/ /,"",$3);print $3}' <<< "$r")
  port=$((BASE_PORT + i)); ctrl=$((CTRL_BASE + i))
  pkill -f "mwboot-control.py --port $ctrl " 2>/dev/null && sleep 1
  dryflag=""; [ "$DRY" = 1 ] && dryflag="--dry-run"
  MWBOOT_KEY="$CKEY" MWBOOT_VLLM_PYTHON="${VENVPY:-python3}" MWBOOT_VLLM_ARGS="$VLLM_ARGS" \
    nohup python3 "$AGENT_DIR/mwboot-control.py" --port "$ctrl" --vllm-port "$port" \
      --gpu "$idx" --max-len "$MAXLEN" $dryflag >"/tmp/mwboot-agent-$ctrl.log" 2>&1 &
  sleep 1
  st=$(curl -s -m 4 "http://127.0.0.1:$ctrl/control/status" || true)
  case "$st" in *'"gpus"'*) c "GPU $idx ($gname): agent up on :$ctrl, endpoint will be :$port";;
    *) die "agent on :$ctrl did not answer - see /tmp/mwboot-agent-$ctrl.log";; esac
  CTRLS+=("$ctrl"); PORTS+=("$port"); IDXS+=("$idx"); NAMES+=("$gname"); VRAMS+=("${vram:-0}"); i=$((i+1))
done

# ---------- 6. enroll each GPU with bake-off (it records THIS machine's address) ----------
HOSTNAME_SHORT=$(hostname -s 2>/dev/null || hostname)
SELF_IP=$(hostname -I 2>/dev/null | awk '{print $1}'); SELF_IP="${SELF_IP:-}"
ENROLLED=0
for j in "${!PORTS[@]}"; do
  payload=$(python3 - "$TOKEN" "${IDXS[$j]}" "${NAMES[$j]}" "$HOSTNAME_SHORT" "${PORTS[$j]}" "${CTRLS[$j]}" "$SELF_IP" "${VRAMS[$j]}" <<'PY'
import json,sys
t,i,g,h,p,cp,ip,v=sys.argv[1:]
print(json.dumps({"token":t,"gpu_index":int(i),"gpu_name":g,"hostname":h,
                  "vllm_port":int(p),"control_port":int(cp),"self_ip":ip,"vram_mb":int(v or 0)}))
PY
)
  resp=$(curl -s -m 10 -X POST "$MP_URL/enroll" -H 'Content-Type: application/json' -d "$payload" || true)
  case "$resp" in
    *'"ok": true'*|*'"ok":true'*)
      mname=$(python3 -c "import json,sys;print(json.loads(sys.argv[1]).get('name',''))" "$resp" 2>/dev/null || true)
      c "GPU ${IDXS[$j]} enrolled as \"${mname:-machine}\""; ENROLLED=$((ENROLLED+1));;
    *)
      warn "GPU ${IDXS[$j]} enrollment failed: ${resp:-no response from $MP_URL}"
      warn "retry later with:  curl -X POST $MP_URL/enroll -H 'Content-Type: application/json' -d '$payload'";;
  esac
done

# ---------- 7. handoff ----------
echo
if [ "$ENROLLED" -eq "${#PORTS[@]}" ]; then
  c "Done. This machine is now in bake-off (Settings > Machines) - tap it into a slot."
  c "No model is loaded yet; the first task you play will load the right one."
elif [ "$ENROLLED" -gt 0 ]; then
  warn "Partially enrolled ($ENROLLED of ${#PORTS[@]}). See the retry lines above."
else
  warn "Agents are running, but enrollment did not reach $MP_URL - check that this box can reach the bake-off machine, then re-run this file."
fi
c "Hand the box back later: evacuate it from bake-off, then here: pkill -f mwboot-control"
c "Agent logs: /tmp/mwboot-agent-*.log · cached weights: ~/.cache/huggingface"
